list=["aiswarya","baby","pallikkarakaran"]
list.append("amelia")
print(list)
list.insert(1,"koovappady")
print(list)
list.extend(["ahg","askdu","uowieut"])
print(list)
list.extend("qwerty")
print(list)